language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
services:
  - rabbitmq
before_script:
  - tests/setup_rabbitmq.sh
install:
  - "pip install -v -r requirements.txt"
  - "pip install -v -r requirements_test.txt"
script: make test
